### ISSUE TITLE
Not working for external server link

### ISSUE THREAD

**Issue by harshzalavadiya** [lslzl3000/node-local-tunnel#1]
i am trying to use this app it works fine when we are using localhost but when i am giving the hostname then it's not working

`
var app = require('express')(); // work with express

var NLTunnel = require('node-local-tunnel');
var options = {
  remoteHost : 'node-zhnebula513447.codeanyapp.com',
  localBase : 'http://localhost:8081'
};
NLTunnel.client(options); // just call client() somewhere with options, you are free to go

var bodyParser = require('body-parser'),
compression = require('compression');
// ...
app.use(bodyParser.json());
app.use(bodyParser.urlencoded());
app.use(compression());
// app.use(express.static('assets/'));
// ...

app.use('/neo', function(req, res, next){
  res.send("from 8081");
});
// .......
app.listen(8081);
`

`
var app = require('express')(); // work with express

// on remote server, init NLT first
var NLTunnel = require('node-local-tunnel');
NLTunnel.init();  // init the tunnel server

// then hannel all logic requests by app.use
app.use( NLTunnel.server() );

// You can also apply routers to relay specific requests, e.g.
// app.get('/foo', NLTunnel.server() ); // only relay /foo with 'GET' request 

// better use NLT before other middleware
var bodyParser = require('body-parser'),
      compression = require('compression');
// ...
app.use(bodyParser.json());
app.use(bodyParser.urlencoded());
app.use(compression());
// app.use(express.static('assets/')); // if you don't want relay static files, put this line before NLT
// ...

app.use('/hello', function(req, res, next){
  res.send("hello")
});
// .......
app.listen(8080);
`

**Comment by lslzl3000** [comment]
Hi, good to know there are some developers using NLT.

I think it's probably your server blocked the 12345 port(the tunnel is actually a WebSocket on port 12345 by default), it's usually blocked if you are using commercial cloud services.

So either you can give a option to use another port or configure the server security policy(if you can).

**Comment by harshzalavadiya** [comment]
I changed the port in node_modules worked like charm

Thank u so much
