### ISSUE TITLE
working with proxy

### ISSUE THREAD

**Issue by harshzalavadiya** [lslzl3000/node-local-tunnel#2]
Actually now i am trying to connect it behind corporate proxy after changing port then it's showing ECONNRESET error

I tried to modify the node module to work with **socket.io-proxy** insted of **socket.io-client** but still it's showing error

so my question is - Is there any way to tunnel websockets with proxy / Access websockets within http proxy?

**Comment by lslzl3000** [comment]
Ok, if you are using socket.io-proxy correctly, I'm afraid that your corporate proxy doesn't add configuration to support WS. WebSocket uses HTTP upgrade mechanism specified in HTTP 1.1 to setup the connection.

e.g. if proxy WS with Nginx, we need to add:

```
# Websocket Support 
proxy_http_version 1.1;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection "upgrade";
```

You should to check if your proxy server support 'HTTP 1.1 with upgrade' .
